CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- client
DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = 'client'
        ) THEN

            DROP TABLE client;
            RAISE NOTICE 'Таблица client удалена.';
        END IF;

        CREATE TABLE client (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                firstName VARCHAR(15) NOT NULL,
                                lastName VARCHAR(40) NOT NULL,
                                birthday DATE NOT NULL,
                                gender SMALLINT CHECK (gender IN (0, 1, 2, 9)),
                                registration_date DATE NOT NULL,
                                address_id INTEGER UNIQUE NULL,
                                FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE CASCADE);
        RAISE NOTICE 'Таблица client создана.';
    END $$;

-- address
DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = 'address'
        ) THEN
            DROP TABLE address CASCADE;
            RAISE NOTICE 'Таблица address удалена';
        END IF;
        CREATE TABLE address (
                                 id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 country VARCHAR(15) NOT NULL,
                                 city VARCHAR(40) NOT NULL,
                                 street VARCHAR(40) NOT NULL);
        RAISE NOTICE 'address';
    END $$;


-- supplier
DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = 'supplier'
        ) THEN
            DROP TABLE supplier;
            RAISE NOTICE 'Таблица supplier удалена.';
        END IF;
        CREATE TABLE supplier (
                                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  name VARCHAR(15) NOT NULL,
                                  address_id INTEGER UNIQUE NULL,
                                  phone_number VARCHAR(15) NOT NULL,
                                  FOREIGN KEY (address_id) REFERENCES address(id));
        RAISE NOTICE 'Таблица supplier создана';
    END $$;

-- images
DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = 'images'
        ) THEN
            DROP TABLE images CASCADE;
            RAISE NOTICE 'Таблица images удалена';
        END IF;
        CREATE TABLE images (
                                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                                data BYTEA NOT NULL);
        RAISE NOTICE 'images';
    END $$;

-- product
DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public'
              AND table_name = 'product'
        ) THEN
            DROP TABLE product;
            RAISE NOTICE 'Таблица product удалена';
        END IF;
        CREATE TABLE product (
                                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(15) NOT NULL,
                                category VARCHAR(40) NOT NULL,
                                price INTEGER NOT NULL,
                                available_stock INTEGER NOT NULL,
                                last_update_date DATE NOT NULL,
                                supplier_id INTEGER NOT NULL,
                                image_id UUID,
                                FOREIGN KEY  (image_id) REFERENCES images (id) ON DELETE SET NULL) ;
        RAISE NOTICE 'product';
    END $$;